### ISSUE TITLE
Total Police Players

### ISSUE THREAD

**Issue by iemand2001** [Kuju29/Fivem_PlayersList#1]
Total Police Players On Activity Status Stays At 0 What Is Incorrect Tryed With Differents Servers Stays At 0 
Any Fix?

**Comment by Kuju29** [comment]
You must have a player name with a similar police rank. For example my server needs to add "[police]" in front of their name.
To display the number simply edit in the config "NAMELIST" or use the command !name <yourpolice name> .

**Comment by iemand2001** [comment]
![Schermafbeelding 2022-12-13 224339](https://user-images.githubusercontent.com/95137018/207450182-90217c7e-227e-47ad-bd17-c1857493afcf.png)

Our Police I Tryed 11 Thats What Police Is For Us 
Its First 11 And Another Number After That How Am I Supposed To Make That Work?
If I Just Typ 11 In NAMELIST I Just Shows That 1 Cop Is Online What Is Incorrect?
Any Help?

Police And Politie Does Not Work At All

**Comment by Kuju29** [comment]
try using this word "[11-"
![image](https://user-images.githubusercontent.com/22098092/207473557-eb9b3c92-0295-4390-816d-1bf502d0a3a7.png)

**Comment by Kuju29** [comment]
They use names in games and discord. Are they the same? Try checking in the command !all

**Comment by iemand2001** [comment]
They Have This In Game But 11 and then some number [11- Does Not Work And 11- Also Does Not Work
If I Try !all it just shows their steam name not ingame name
![image](https://user-images.githubusercontent.com/95137018/207597664-47bd6591-e680-4786-92a0-c7598300d49e.png)

Any Clue?

**Comment by Kuju29** [comment]
This cannot be done, fivem will only show the stream name in the database. You can check it using this url http://{yourip:yourport}/players.json.

**Comment by iemand2001** [comment]
Oh Okay Thanks For Your Help Anyway
