### ISSUE TITLE
JSON information retrieval issue and stuck player counter on cfx.re - Server marked as offline

### ISSUE THREAD

**Issue by Jeanyvon22** [Kuju29/Fivem_PlayersList#2]
I would like to ask if anyone knows why the bot is not retrieving JSON information from http://185.200.244.102:30120/players.json and that I have noticed on the cfx.re website, the player counter remains at 1 all the time https://cfx.re/join/3lq45r. As a result, this server is always marked as offline. P.S.: It is offline when I run it on railway.app, but when I execute it from Visual Studio, there are no issues.

**Comment by Kuju29** [comment]
Try opening the url http://185.200.244.102:30120/players.json and https://cfx.re/join/3lq45r. in your server for checking online players.
If everything is normal, set `"Log_update": true`  in `config` to see if there is an error.
